---
- name: Installing a software package on all hosts
  hosts: all
  become: true
  tasks:
    - name: Installing NGINX
      apt:
        name: nginx
        state: present
    
    - name: Starting NGINX
      service:
        name: nginx
        state: started

    - name: Installing Python
      apt:
        name: apache2
        state: present

    - name: Starting Apache
      service:
        name: apache2
        state: started